echo "[req]"
echo "distinguished_name = req_distinguished_name"
echo "req_extensions = v3_req"
echo ""
echo "prompt = no"
echo ""
echo "[req_distinguished_name]"
echo "commonName = $COMMON_NAME"
echo ""
echo "[v3_req]"
echo "keyUsage = nonRepudiation, digitalSignature, keyEncipherment"
echo "$EXTEND_KEY_USAGE"
echo "subjectAltName = @alt_names"
echo ""
echo "[alt_names]"
echo "DNS.1 = $COMMON_NAME"
echo "DNS.2 = $DNS2"
if [ "$ROUTE_ENABLED" = true ]; then
    echo "DNS.3 = $DNS3"
fi
