###############################################################################
#
# © Copyright IBM Corp. 2024
#
###############################################################################
# Default values for IBM Connectivity pack.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
skipHooks: true
namespace: ''
license:
  accept: false
replicaCount: 1 # Replica of the POD
bunyan: "'{\"loglevel\" : \"info\", \"logsrc\" : true, \"logstdouttext\" : {}}'" # Override Log configuration
environmentVariables: {} # Yaml object ENV to be added on action and event pods
architecture: amd64
annotations:
  productName: IBM Connectivity pack
image:
  registry: us.icr.io # Image registry base URL
  path: conn-pack-prod-ns
  imagePullSecretName: '' # Image pull secret name if already  exist please specify here else give below values for creating new Image pull secret
  imagePullEmail: dummyEmail # Image pull secret email ID
  imagePullUsername: iamapikey # Image pull username 
  imagePullPassword: dummyPassword # Image pull password 
certificate:
  enable: true # Enable MTLS or TLS
  MTLSenable: false # Enable MTLS if true else fallback to TLS
  generate: false # generate new certificates use this for certificate rotation
  clientSecretName: '' # If MTLS/TLS secret for client already exist please specify here
  clientCertPropertyName: 'tls.crt'
  clientCertKeyPropertyName: 'tls.key'
  clientCertPKCSPropertyName: 'pkcs.p12'
  serverSecretName: '' # If MTLS/TLS secret for server already exist please specify here
  serverCertPropertyName: 'tls.crt'
  serverCertKeyPropertyName: 'tls.key'
  caCertPropertyName: 'ca.crt'
  pkcsPassword: 'admin123' # pkcs.p12 password
route:
  enable: true # generate OpenShift route for external access
  domain: 'example.com' # subdomain of OpenShift cluster where connector service is being deployed
basicAuth:
  enable: false # Enable basic auth for service 
  username: 'csuser'
preHook:
  image: connectivity-pack-prehook
  tag: 20250213-060448-amd64
proxy:
  name: connectivity-pack-proxy
  image: connectivity-pack-proxy
  tag: 20250529-075002-amd64
enableRefreshTokenMode: false # Enable refresh token mode
action:
  name: action-connectors
  image: action-connectors
  resources: # Update below value for vertical scaling of container
    limits:
      cpu: '1'
      ephemeral-storage: 10Gi
      memory: 512Mi
    requests:
      cpu: 250m
      ephemeral-storage: 5Gi
      memory: 256Mi
  tag: 20250529-075926-amd64
event:
  enable: false # Set to true if Event container is needed
  name: event-connectors
  image: event-connectors # Update image
  resources: # Update below value for vertical scaling of container
    limits:
      cpu: '1'
      ephemeral-storage: 10Gi
      memory: 750Mi
    requests:
      cpu: 250m
      ephemeral-storage: 5Gi
      memory: 400Mi
  tag: 20250207-054839-amd64
javaservice:
  enable: false # Set to true if Java container is needed
  name: java-tech-connectors
  image: java-tech-connectors # Update image
  resources: # Update below value for vertical scaling of container
    limits:
      cpu: '1'
      ephemeral-storage: 10Gi
      memory: 750Mi
    requests:
      cpu: 250m
      ephemeral-storage: 5Gi
      memory: 400Mi
  tag: 20250529-030020-amd64
autoScaling:
  enable: false # Update this to true to enable autoScaling
  minReplicas: 1 # What is the minimum replica needed
  maxReplicas: 5 # What is the maximum replica needed
  cpuUtilization: 70 # % of CPU utilization after which POD to be replicated 
  memoryUtilization: 70 # % of Memory utilization after which POD to be replicated 
securityContext:
  capabilities:
    drop:
      - ALL
  privileged: false
  runAsNonRoot: true
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  seccompProfile:
    type: RuntimeDefault
csCommon:
  eventList: "['salesforceevent']"
